### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'which_model'

### ISSUE THREAD

**Issue by xpirad** [Zheng222/PPON#6]
Hello, i'm trying to run your code from latest commit
But there is an attributeError

Namespace(cuda=True, isHR=True, models='ckpt/PPON_G.pth', only_y=True, output_folder='result/Set5/', test_hr_folder='Test_Datasets/Set5/', test_lr_folder='Test_Datasets/Set5_LR/', upscale_factor=4, which_model_G='ppon')
Traceback (most recent call last):
  File "test_PPON.py", line 50, in <module>
    model = networks.define_G(opt)
  File "/home/fw/Upscale/PPON/models/networks.py", line 76, in define_G
    if args.which_model == 'content':
AttributeError: 'Namespace' object has no attribute 'which_model'

Can you help me fix that? Thanks!

**Comment by Zheng222** [comment]
@xpirad Hello, we have fixed this issue.

**Comment by xpirad** [comment]
Thanks, but it still can't run... It says AttributeError: 'Namespace' object has no attribute 'alpha'

**Comment by Zheng222** [comment]
@xpirad Now, it can work.

**Comment by xpirad** [comment]
Thanks..
